### ISSUE TITLE
contains()-check fails

### ISSUE THREAD

**Issue by Zasch** [ByteLegendQuest/java-fix-broken-javadoc#52]
In ChallengeTest.java there is an assertion

`Assertions.assertTrue(document.text().contains("Location: C:\\users\\Documents"));`

which fails. If you modify the assertion like so:

`Assertions.assertTrue(document.text().contains("Location: C:\\"));`

the test will pass. If you put one more character behind `\\` it stops working (e.g. `Assertions.assertTrue(document.text().contains("Location: C:\\u"));` will not work).

**Comment by blindpirate** [comment]
This is intentional. Have you checked javadoc output HTML of your PR https://github.com/ByteLegendQuest/java-fix-broken-javadoc/pull/51/files ? Your answer is wrong.
